### ISSUE TITLE
Time series analysis

### ISSUE THREAD

**Issue by mao1756** [mao1756/tlhcrimemap#28]
This issue is to write down the idea about time series analysis on the data.

- Is it possible to capture the increasing/decreasing trend at each location? Downtown / others?
- Is there any difference between summer and other seasons since the students will be out?

**Comment by abdullahnaeemmalik** [comment]
Time series analysis would be better suited for Bullet 2, whereas k-means clustering would be better suited for Bullet 1, no?

**Comment by mao1756** [comment]
It is not feasible to finish this on time.
