### ISSUE TITLE
Crime distribution per hour or day/night

### ISSUE THREAD

**Issue by mao1756** [mao1756/tlhcrimemap#32]
We would like to plot the crime distribution with respect to time. In particular, we would want to plot:

- The total number of crimes at each hour across all days
-  The total number of crimes in more broader category of hours (day/night)

**Comment by abdullahnaeemmalik** [comment]
I believe Cagatay finished doing this, no?

**Comment by mao1756** [comment]
@abdullahnaeemmalik Correct, but i think he hasn’t uploaded the change to GitHub. @ayhncgty Could you make a pull request on the change you showed me last week?
